# Generated by Django 3.2.16 on 2022-12-07 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='user',
            new_name='admin',
        ),
    ]
