# Generated by Django 3.2.16 on 2022-11-07 05:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_file_name', models.CharField(default='No template file name', max_length=256)),
                ('file', models.FileField(null=True, upload_to='template_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xlsm', 'xlsb', 'xltx', 'xls'])])),
                ('user_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file_name', models.CharField(default='No data file name', max_length=256)),
                ('file', models.FileField(null=True, upload_to='data_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xlsm', 'xlsb', 'xltx', 'xls'])])),
                ('user_id', models.IntegerField(default=0)),
                ('template_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_handler.templatefile', verbose_name='Файл шаблона')),
            ],
        ),
    ]
