# Generated by Django 3.2.16 on 2022-11-15 08:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=256)),
                ('file', models.FileField(null=True, upload_to='files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xlsm', 'xlsb', 'xltx', 'xls'])])),
            ],
        ),
        migrations.CreateModel(
            name='TemplateExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=256)),
                ('file', models.FileField(null=True, upload_to='files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xlsm', 'xlsb', 'xltx', 'xls'])])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DataFile',
        ),
        migrations.DeleteModel(
            name='TemplateFile',
        ),
        migrations.AddField(
            model_name='dataexcel',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_handler.templateexcel', verbose_name='Template id'),
        ),
        migrations.AddField(
            model_name='dataexcel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
