# Generated by Django 3.2.16 on 2022-11-21 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler', '0002_auto_20221115_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataexcel',
            name='file',
            field=models.FileField(null=True, upload_to='data_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xlsm', 'xlsb', 'xltx', 'xls'])]),
        ),
        migrations.AlterField(
            model_name='templateexcel',
            name='file',
            field=models.FileField(null=True, upload_to='template_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xlsm', 'xlsb', 'xltx', 'xls'])]),
        ),
    ]
