# Generated by Django 3.2.16 on 2022-12-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler', '0003_auto_20221121_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateexcel',
            name='template_type',
            field=models.BooleanField(null=True),
        ),
    ]
