# Generated by Django 3.2.16 on 2022-11-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userverificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualuser',
            name='iin',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='individualuser',
            name='ip_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='juridicaluser',
            name='bin',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='juridicaluser',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
