# Generated by Django 3.2.16 on 2022-11-21 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20221121_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='service_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.serviceplan'),
        ),
    ]
