# Generated by Django 3.2.16 on 2022-11-30 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20221121_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='individual_user', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='juridicaluser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='juridical_user', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmployeeUser',
            fields=[
                ('position', models.CharField(max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employee_user', serialize=False, to='user.user')),
                ('juridical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_juridical', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
