# Generated by Django 3.2.16 on 2022-12-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20221130_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='juridicaluser',
            name='bank',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='juridicaluser',
            name='iban',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='juridicaluser',
            name='kbe',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='juridicaluser',
            name='official_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='juridicaluser',
            name='post_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='juridicaluser',
            name='swift',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
