# Generated by Django 3.2.16 on 2022-12-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_juridicaluser_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='method',
            field=models.CharField(choices=[('CARD', 'card'), ('OTHER', 'other'), ('UNKNOWN', 'unknown')], default='UNKNOWN', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='service_plan',
            field=models.CharField(choices=[('SILVER', 'silver'), ('GOLD', 'gold'), ('PREMIUM', 'premium'), ('UNKNOWN', 'unknown')], default='UNKNOWN', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'success'), ('FAILURE', 'failure'), ('UNKNOWN', 'unknown')], default='UNKNOWN', max_length=10),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='PaymentStatus',
        ),
        migrations.DeleteModel(
            name='ServicePlan',
        ),
    ]
