# Generated by Django 3.2.16 on 2022-12-06 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20221206_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_log', to=settings.AUTH_USER_MODEL),
        ),
    ]
