# Generated by Django 3.2.16 on 2022-12-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_paymentlog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='method',
            field=models.CharField(choices=[('card', 'Card'), ('other', 'Other'), ('unknown', 'Unknown')], default='UNKNOWN', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='service_plan',
            field=models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('premium', 'Premium'), ('unknown', 'Unknown')], default='UNKNOWN', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('unknown', 'Unknown')], default='UNKNOWN', max_length=10),
        ),
    ]
