# Generated by Django 3.2.16 on 2023-01-27 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('Juridical', 'Juridical'), ('Individual', 'Individual')], max_length=10)),
                ('price', models.IntegerField(default=0)),
                ('max_user', models.SmallIntegerField(default=0)),
                ('expiration_days', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServicePlanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_plan_status', models.BooleanField(default=False)),
                ('payment_status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('unknown', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('method', models.CharField(choices=[('card', 'Card'), ('other', 'Other'), ('unknown', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('service_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_plan_payments', to='payments.serviceplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
