# Generated by Django 3.2.16 on 2023-02-03 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_auto_20230203_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceplanpayment',
            name='service_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.serviceplan'),
        ),
        migrations.AlterField(
            model_name='serviceplanpayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_plan_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
