# Generated by Django 3.2.16 on 2023-02-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20230203_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceplanpayment',
            name='method',
            field=models.CharField(choices=[('card', 'Card'), ('other', 'Other'), ('unknown', 'Unknown'), ('admin', 'Admin')], default='UNKNOWN', max_length=10),
        ),
    ]
