# Generated by Django 3.2.16 on 2023-02-15 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_serviceplanpayment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceplanpayment',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='serviceplanpayment',
            name='date',
        ),
    ]
