# Generated by Django 3.2.16 on 2023-04-03 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20230215_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceplanpayment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 3, 10, 19, 54, 483403)),
        ),
    ]