# Generated by Django 3.2.16 on 2022-12-26 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='admin_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='admin_applications', to='user.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='author_applications', to='user.user'),
            preserve_default=False,
        ),
    ]
